### ISSUE TITLE
please correct results directory

### ISSUE THREAD

**Issue by asishallab** [LzLang/Zendro-Converter#10]
In the current `results` directory there are four data-model-definition files, directly at root level:
- `Study.json`,
- `Test_Food.json`, and
- `Test_Food_expected.json`

They were used erroneously in an attempt to launch a Zendro data-warehouse with them and
caused errors. 

Please remove them from the results directory.

If they stem from unit tests, please adjust the unit test to use another directory. In testing,
one should never mix test and true results. This goes for directories, but also databases, file-servers,
etc.

**Comment by LzLang** [comment]
These files were remainings of a unit-test.
I removed `Study.json` and moved the other two files to a separate folder ([unit-test](../tree/main/unit-test)).

In the future, the separate directory will be used for unit-test.

At the moment, the script creates an analogous structure to the input directory in the output folder.
Unfortunately, subfolders lead to an error when starting Zendro.
A possible solution would be to do without subfolders in the output directory in future versions (sacrifice order/structure in favor of usability/comfort).
