### ISSUE TITLE
Include model name and storage type in Zendro model definitions 

### ISSUE THREAD

**Issue by asishallab** [LzLang/Zendro-Converter#5]
# Extend the existing code to include model name and storage information

A [typical Zendro data model definition](https://zendro-dev.github.io/setup_root/data_models#json-specs) requires these two additional arguments:
* extend your script to use named command line arguments, e.g. with [`argparse`](https://docs.python.org/3/library/argparse.html)
* the _name_ of the data model, e.g. `"model" : "book"`. Extract this from the BrApi-file-name.
* the _storage-type_ (command line arg `-s` or `--storage-type`), e.g. `"storageType" : "sql"`. Provide an optional third argument to your script. This is the storage type to be used for _all_ generated Zendro models. (for details see below)
* add a default primary key to _all_ data models (command line argument `-p` or `--primary-key-name`). By default this is set to `id` and of type `Int`. 
* Add another optional argument (`-t` or `--primary-key-type`). By default this is `Int` but can be `String`. Make sure to validate this and inform the user about the possible two types (see docu of `argparse` about how to add usage information).
* In the usage of your programm inform the user that if _any_ of the primary key related arguments are given, identifiers are created that Zendro will not take care of _automatically_, meaning that _no database sequence_ will be used to automatically populate the primary key (`id`) property of _new_ records. However, the user can write a Zendro migration to add e.g. a database sequence to do exactly that for his custom primary keys.  
* Make sure the current properties become the key-value pairs of an `attributes` object of the Zendro definition. See this example for details:
```json
{
  "model" : "book",
  "storageType" : "sql",
  "attributes" : {
    "title" : {"type":"String", "description": "The book's title"},
    "publisher_id": "Int"
  }
}
```

## Storage-Type details

If this argument is _not_ provided, use `sql` as default storage-type. If it is provided, validate that it is correctly spelled and one of the accepted storage-types (see Zendro documentation). If not inform with a meaningful error message. Put this optional argument in your usage information, too.

**Comment by LzLang** [comment]
I tried to implement what you requested, here is a current example of the result.

Example of [Study](results/BrAPI-Core/Study.json):
```json
{
    "model": "Study",
    "storageType": "sql",
    "attributes": {
        "primary_id": "Int",
        "active": {
            "description": "Is this study currently active",
            "type": "Boolean"
        },
        "commonCropName": {
            "description": "Common name for the crop associated with this study",
            "type": "String"
        },
        "culturalPractices": {
            "description": "MIAPPE V1.1 (DM-28) Cultural practices - General description of the cultural practices of the study.",
            "type": "String"
        }
}
```
