### ISSUE TITLE
Extend list of supported scalar types 

### ISSUE THREAD

**Issue by asishallab** [LzLang/Zendro-Converter#8]
# Support all scalar data types, Zendro has

Zendro supports the following [data types](https://zendro-dev.github.io/setup_root/data_models#supported-data-types)

Check, which of these are used in BrApi and add them to your translator. Even if some or not supported or not used by BrApi, use the [JSON Schema scalar terms](https://json-schema.org/draft/2020-12/json-schema-core.html#name-instance-data-model).

After this issue is solved, please inform Peter Selby and me in an email about:
- this extension
- what JSON Schema types are used and not used in BrApi
- what not used we support in our translator none the less

**Comment by LzLang** [comment]
The converter currently supports the following datatype:
- String
- Integer
- Float/Number
- Boolean

Therefore, all of BrAPIs data types are supported, except "array" and "object".
